import "./globals.css";
// Components
import Sidebar from "./components/sidebar/Sidebar";
// Context
import { GlobalProvider } from "./context/GlobalContext";

export const metadata = {
  title: "Prueba Técnica",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GlobalProvider>
          <Sidebar />
          <div className="p-4 sm:ml-64">{children}</div>
        </GlobalProvider>
      </body>
    </html>
  );
}
